language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: 'packages/tusharm.com/bin'
  target-branch: master
  on:
    branch: develop
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - yarn lint
before_install: yarn global add greenkeeper-lockfile@2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
