language: node_js
node_js:
- '0.11'
after_script:
- sh deploy.sh
branches:
  only:
  - develop
env:
  global:
    secure: EdmU/ruoWp0x9bApO32a/qW8PJaeajyUCMicPPxkR7jWOAYNzOFZdjhWWd/oRG7yr6Y3p8GBblzK1Ufax3porENeyRLonu1PqJmNik7fZ1Fj+QoZR9Z8yXY6TufTBTM36MQRyGZx2DOGTmvjSgDK3fOTX5suHVqx4NEKHJQdbLU=
